data:
  augment: true
  batch_size: 128
  compute_length_stats: true
  crop: false
  csv_path: /mnt/disks/sdb/VesselReIdentification/data/train.csv
  image_root: /mnt/disks/sdb/VesselReIdentification/data/images/raw
  image_size: 224
  length_mean: 221.2029
  length_std: 44.8894
  normalize: false
  num_workers: 8
  pk_sampler:
    batches_per_epoch: 1000
    enabled: true
    k: 8
    p: 8
  rotate: false
  use_length: true
eval:
  max_fpr: 0.01
  threshold: 0.7
faiss:
  normalize: true
gallery:
  csv_path: /mnt/disks/sdb/VesselReIdentification/data/gallery.csv
  image_root: /mnt/disks/sdb/VesselReIdentification/data/images/raw
  image_size: 224
  length_mean: 221.2029
  length_std: 44.8894
  use_length: true
model:
  backbone: resnet50
  embedding_dim: 512
  length_embed_dim: 32
  pretrained: true
  use_length: true
query:
  csv_path: /mnt/disks/sdb/VesselReIdentification/data/query.csv
  image_root: /mnt/disks/sdb/VesselReIdentification/data/images/raw
  image_size: 224
  length_mean: 221.2029
  length_std: 44.8894
  use_length: true
seed: 1337
train:
  arcface_margin: 0.3168455017269976
  arcface_scale: 15
  arcface_weight: 0.09494483411867943
  epochs: 40
  log_every: 50
  loss: combined
  lr: 9.4493820377825e-05
  margin: 0.3
  triplet:
    distance: cosine
    margin: 0.3713223467790952
    softplus: true
  triplet_weight: 2.139761177702229
  weight_decay: 1.0e-05
