model:
  backbone: resnet50
  embedding_dim: 512
  use_length: true
  length_embed_dim: 32

faiss:
  normalize: true

gallery:
  image_size: 224
  use_length: true
  length_mean: 221.2029
  length_std: 44.8894
